services:
    app.manager.category:
        class: AppBundle\Manager\CategoryManager
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    app.manager.post:
        class: AppBundle\Manager\PostManager
        arguments: ["@doctrine.orm.entity_manager"]
        public: true